[project]
name = "aw-import-screentime"
authors = [{name = "Erik Bjäreholt", email = "erik@bjareho.lt"}]
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aw-client>=0.5.15",
    "aw-core>=0.5.17",
]

[project.scripts]
aw-import-screentime = "aw_import_screentime.main:main"